# Generated by Django 4.0.4 on 2022-05-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CovidData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(blank=True, max_length=1000, null=True)),
                ('country_code', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_cases', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_deaths', models.CharField(blank=True, max_length=2000, null=True)),
                ('total_recovered', models.CharField(blank=True, max_length=2000, null=True)),
            ],
        ),
    ]
